{% set version = "1.2-17" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-scam
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/scam_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/scam/scam_{{ version }}.tar.gz
  sha256: b33de62a18da930ceee2db73cd951fb47d5855bb58c80331eee2730437e30502

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-mgcv >=1.8_2
  run:
    - r-base
    - r-matrix
    - r-mgcv >=1.8_2

test:
  commands:
    - $R -e "library('scam')"           # [not win]
    - "\"%R%\" -e \"library('scam')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=scam
  license: GPL-2.0-or-later
  summary: Routines for generalized additive modelling under shape constraints on the component functions of the linear predictor (Pya and Wood, 2015) <doi:10.1007/s11222-013-9448-7>. Models can contain multiple shape constrained (univariate and/or bivariate) and unconstrained terms. The routines of gam() in package 'mgcv'
    are used for setting up the model matrix, printing and plotting the results.  Penalized likelihood maximization based on Newton-Raphson method is used to fit a model with multiple smoothing parameter selection by GCV or UBRE/AIC.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: scam
# Version: 1.2-12
# Author: Natalya Pya <nat.pya@gmail.com>
# Maintainer: Natalya Pya <nat.pya@gmail.com>
# Title: Shape Constrained Additive Models
# Date: 2021-08-10
# Description: Routines for generalized additive modelling under shape constraints on the component functions of the linear predictor (Pya and Wood, 2015) <doi:10.1007/s11222-013-9448-7>. Models can contain multiple shape constrained (univariate and/or bivariate) and unconstrained terms. The routines of gam() in package 'mgcv' are used for setting up the model matrix, printing and plotting the results.  Penalized likelihood maximization based on Newton-Raphson method is used to fit a model with multiple smoothing parameter selection by GCV or UBRE/AIC.
# Depends: R (>= 2.15.0), mgcv (>= 1.8-2)
# Imports: methods, stats, graphics, Matrix, splines
# Suggests: nlme
# License: GPL (>= 2)
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2021-08-10 13:41:25 UTC; natalya
# Repository: CRAN
# Date/Publication: 2021-08-10 14:40:02 UTC
